=== Adrianotiger/desktopPet/Resources/animations.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema
    elementFormDefault="qualified"
    attributeFormDefault="unqualified"
    targetNamespace="http://esheep.petrucci.ch/"
    xmlns="http://esheep.petrucci.ch/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name='animations'>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name='header' minOccurs='1' maxOccurs='1'>
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name='author' type='xsd:string' minOccurs='1' maxOccurs='1' />
              <xsd:element name='title' type='xsd:string' minOccurs='1' maxOccurs='1' />
              <xsd:element name='version' type='xsd:string' minOccurs='1' maxOccurs='1' />
              <xsd:element name='info' type='xsd:string' minOccurs='1' maxOccurs='1' />
              <xsd:element name='application' type='xsd:integer' minOccurs='1' maxOccurs='1' />
              <xsd:element name='home' type='xsd:string' minOccurs='0' maxOccurs='1' />
              <xsd:element name='icon' type='xsd:string' minOccurs='1' maxOccurs='1' />
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name='image'>
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name='tilesx' type='xsd:integer' minOccurs='1' maxOccurs='1' />
              <xsd:element name='tilesy' type='xsd:integer' minOccurs='1' maxOccurs='1' />
              <xsd:element name='png' type='xsd:string' minOccurs='1' maxOccurs='1' />
              <xsd:element name='transparency' type='xsd:string' minOccurs='1' maxOccurs='1' />
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name='spawn' maxOccurs='100'>
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name='x' type='xsd:string' minOccurs='1' maxOccurs='1' />
              <xsd:element name='y' type='xsd:string' minOccurs='1' maxOccurs='1' />
              <xsd:element name='next' maxOccurs='1'>
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base='xsd:integer'>
                      <xsd:attribute name="probability" type="xsd:integer" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="probability" type="xsd:integer"/>
            <xsd:attribute name="id" type="xsd:int"/>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name='animation' minOccurs='1' maxOccurs='256'>
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name='name' type='xsd:string' minOccurs='1' maxOccurs='1' />
              <xsd:element name='start' minOccurs='1' maxOccurs='1'>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name='x' type='xsd:string' minOccurs='1' maxOccurs='1' />
                    <xsd:element name='y' type='xsd:string' minOccurs='1' maxOccurs='1' />
                    <xsd:element name='interval' type='xsd:string' minOccurs='1' maxOccurs='1' />
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name='end' minOccurs='0' maxOccurs='1'>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name='x' type='xsd:string' minOccurs='1' maxOccurs='1' />
                    <xsd:element name='y' type='xsd:string' minOccurs='1' maxOccurs='1' />
                    <xsd:element name='interval' type='xsd:string' minOccurs='1' maxOccurs='1' />
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name='sequence' minOccurs='1' maxOccurs='1'>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name='frame' type='xsd:integer' minOccurs='1' maxOccurs='512' />
                    <xsd:element ref='next' maxOccurs='100' />
                    <xsd:element name='action' type='xsd:string' minOccurs='0' maxOccurs='64' />
                  </xsd:sequence>
                  <xsd:attribute name="repeat" type="xsd:string"/>
                  <xsd:attribute name="repeatfrom" type="xsd:integer"/>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name='border' minOccurs='0' maxOccurs='1'>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element ref='next' />
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name='gravity' minOccurs='0' maxOccurs='1'>
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element ref='next' />
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="id" type="xsd:integer"/>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:simpleType name="curr">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="none" />
      <xsd:enumeration value="taskbar" />
      <xsd:enumeration value="window" />
      <xsd:enumeration value="horizontal" />
      <xsd:enumeration value="horizontal+" />
      <xsd:enumeration value="vertical" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:element name="next">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base='xsd:integer'>
          <xsd:attribute name="probability" type="xsd:integer" />
          <xsd:attribute name="only" type="curr" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="only">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="next" />
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== Adrianotiger/desktopPet/Docs/ball.xml
<?xml version="1.0" encoding="utf-8"?>
<animations xmlns="http://esheep.petrucci.ch/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://esheep.petrucci.ch/ https://raw.githubusercontent.com/Adrianotiger/desktopPet/master/Resources/animations.xsd">
  <header>
    <author>Adriano</author>
    <title>ball</title>
    <version>1.0</version>
    <info>Simple ball, bouncing from left to right on the screen</info>
    <application>1</application>
    <home>iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAYdEVYdFNvZnR3YXJlAHBhaW50Lm5ldCA0LjAuNvyMY98AAEtbSURBVHhe7Z13nF1Xfe0pxkU2li1Z1eqSLcmSJVe5Nww2xYRiOtiUBIeEUF4SkhBCEghJeAnwSCBg3NR773XUe9eol1EdTe/13juj+b3v2jr7es/VGWlUMYE/1ufce+4p++y1fuu39p0Z6W1L3tbuD/g9RuzOP+D3B7E7/4DfH8Tu/F8Gu4SIu/7vNGJ3/i9AmrRl13S2tR362dbeQ2zvkAft2AOPW8ljT1niPe81e/xxa7rvPrN77rGmBx+0pve8x2qeeq8VPva05dz7qO0aeL9t6j7IVt3Uy7LecUsoBCHuvr9ziN35O4o0OUvf1dE23DrQsu8YZvvvfcyOPPK05T/1rJU/80FLfOBD1vT+91vTE09Y0/33W9Odd1rToEFmd91lTQ89ZE1PP21NH/qQ1bz/g1byvg9a7hPPWM5D77E9dz1i2267x9bc0jcUgUfceH4nELvzdwTNSMgC667pYDtv7maHu/a1gj4DrGLAYKsbPMQah95lNmSINQ0ebE0DBpj162dNvXtbU7du1tS5s1mnTmZdu1pTjx5mffpY0+23W9PAgafFgTBSQ4ZazaAhVnr7IMvt1d8OdOpt297d1VZfdYYreMSN9y2J2J1vYTSb6A1te9iBdt2s8MZbrP66682uvtqahGuusaZrrzUD2jaDPhM4zh3/rne9CX8u0Ln+/DOu48+/7jqruv5Gy72pk+1q38NWtenabHwg7hneUojd+RZDs0ldfm0X29H7Tsu772FLYdmnqORTN99sJtLe9rYri7e/3axNG2vq0ME5S+1Dj9rhoQ/a5i79m405Qtyz/dYRu/MtgvTkLX9He9vepqMdad/VKnv0tkYsvBHiG7DtxrZtT1frO98ZT9LlhpwDEZxq185Ode9uTWoht91mpV2626Gbuthm2lL4LCDuWX9riN35FsBp4knw+7v0sapOXSx1ww2WuuoqS73jHQ5JgQpMCRDREAPtz/ysMQYtfX7qHAiPbWQcjYzpFGiKtqfUUnCn0s7dLLtjn7ekEGJ3/haRnqBtXW6z4qH3WqpvX0tSXXEW36SJByLOk50MkIiQ/gxSnIio2hTXa8A5GujjKYHXKQhLiwxCQ2G0BN1f48gcm4NaxPXX26mOHe0UAfTEoHtsXdvuoQiEuHm4Yojd+VtAekK2v7uL5d3SxerpqymqJ8kEJiDLVReT2hLhnuz6AH6fO4bzExCdvPFGS+q6uj4rgNStt1pS4HWyffvTn+s4iYTzwntkQp+FQtD4zhABgpLQGt/9bjt1yy2W6NDRjtHKNrbpHIpAiJuXy47YnVcQ6QnYcEsfO9nvDkv26mX12L0mWJOqrcisi1AbwO2jyuoht54MUM9k10FcvUA1J5j4BBMvskVyQm7C8i7J8i55992Wuv9+FyQd7rvPUuxPsARMMIYE+cIJgvMlnISux/UduFeCe/o2FIoiE15EXhzOXbhuQ//+drj3QFvZfOUQN0eXFbE7rxDcQy+7qoPtpc/XDhho9azD67D7Ri2x/IQBT3xNBpwQILmOyqonFNZDYP0DD1jiiScs8cwzlnzuOUt+4hOW+vznLfXii5b88pct9cd/bKk/+RNLvfSSNXzta9bw9a9bSvjTP7UUnyc5NvnJT1ryox+11Ac/aKn3vc+STz5pyYcftiSCSQ4daknIS/bsaUmsXQJzYmMsLUHPkHYEoNCocxVkK/oNsO3teoQiuKJCiN15BeAedGunvlbYoYvVQWISm69hIqupsBqqyle5iK4GVRGavaaaarpwPtVc/4EPWOIrX7Hkd75jqR/9yFL/9V/W8Oqr1jBmjDVOnHga48ZZ4+jR1jhihDW+8cZp8Lph+HBreO01a3j5ZUv98peW+n//z1L/+Z/W8OMfW4Ou9Y//aKm/+RtLfeMbTkTJ55+35NNPOxepRwh1N9102nUYUwjvWnrtxSBXkHvo+AYJXc+OIE506Uk+aCaEuHm75IjdeRmRfsB9/e+y2nvvtWp6rg9RmqiQYI9KAWFUMlHVTHY11VONpddQ8bVUej3VnYCg5E9/aikROn26NSxZYo1r11rj1q12ascOO6Xt+vV2avVqO7VsmZ3S54sWncbChdY4b541zpp1+twpU6xhwgRrGDvWGkaNshTiSP3P/zhRJP/pnyz1rW85R0ngMPW0j7oBA6y+Wzerx9rraF8StFpRLUR7IXuEgkg7gt6TQSqGPWRbuzb7DiFuDi8pYndeJriHWnF1R8vp1tcqWS/Xdupk1VSBD3WaIBFeEYNK1vtVd9xhtVReHTZdDwmJH/7Qkr/4haVGjrSUSIPEBshtgOiGbduscedOa9y9204J2dl2avNma+SzRkTQuGKFNS5dao1eCPPnW+Ps2dYwY4Y1TJ1qDThGA47RgGOkcIqU3OG//9uS//EflvrBD5wjJP/8zy3xhS9Y/Uc+Yolnn3Wtp54sUdevn9WSO2rIDt7BhLB1SQh6bglA+aBeYVeivu02292x1xUTQezOywD3MOtu7G4n+w+ycogvI0hVYfWZRJfHoAKRVBHearDe+u9+15Kvv24piGugqhv37LFTBw5Y4/797nUDZDdou3evey8RnNq+3U5t2WKnNmw47QorV1qjhKJrLFhgjXPnuupvnDbNGiZPPl39tA7nJrrXb35jqV/9ylKILan28JOfWOrf/92SCDDBeOr/8i8t8c1vWoIcUf+Zz1gdmaEWV6jBqWpobV4AmfCCEBRm69TScI9a2koOAXHpO5v9rCFuXi8asTsvMdwDbLqpuxX3H2jlBJ8ybFIToEoQ6WUBSrWF8HKWapVMRNWQIVb93vdaLcGtXpM+frw1qIIPHbJThYV2qqzMmsCpoiI7lZtrjUePWuPhw+5ziULV30j1N8oRNm067Q6c34ADpHCAFNXfQPU3zJnjqj9F9acmTbIU1Z9U9ZMPkrSAJCJI/vrXliAjyHWSP/+5JRBC4l//1eppC4l/+AdL/O3fWj2uUEvwrH38cath7V/TvbtVE2yreOYqxFAl4fOMITQXagtyQW1rCbU1rEaO97rdVl3T6bKKIHbnJYQb+I62Xa2EsFYGqSK/jH7uq1uECyUByuillQSsatJ4HQEsAQkpCEqtWmWN6uc5OY5sR3ppqTUB9/rkSWs8duy0AA4efFMAagW4QCMtoMG7ANdqWL7cOUmKDJBS+8AFUmQAtZMULSBJBkiRAZK0gCSBUiJI4ARJiYCQeYYA/u7vrP7b33Zirf30p62GVUTNY49Z9V13WRUtrwpilWMqqXTlGu96XgQqCLmBEwqri2qOL+h8q21o/p1B3DxfMGJ3XiK4Ae/u2NNK6W0lPFAxNucJLwZFEfS6mEkpQRilhLyKe+6x6s99zupI4cnFix2hjuCSElftIryJ9w7sO1VcfNoNJIDjx+2UjkcADb4t7NplDQingTaQ2rjRGtatcy6QwgUacAHdI0krkMiSM2daklaQpBUkaAVJWkGCjJFABAlEUE8WkAgS5IF6Qmf9v/2b1f3zP1v9979v9X//91bHKqSOfFJHO6j94hetBjeoJh9Us4Ss7NvXKsgGFWSDCuYi3eIy4J2hkiBZiXuUd+9hW9p2uywiiN15CeAGuqtLb0d+sQIcqpbFq8JFeCEoiOBEwIOWYfcVqhomsF6VRmU2QGRTZaU11ddbU12dNdXWWlN1tTVVVKTFkBZAXp41njhhp44caS4A5QIJgMyQ8m1gzRpLkQUUGpO4gO4lF0gSBJO0giStIEErSNIKErSCBHkgQR6of+UVS0gErArqyQP1iLTuX/7F6iUC3KqOTFD3V39ldX/xF1b71a9aDSGx+mMfs+r3vMcqWfVUYO0VXbtaBXNSTr8vD4TgIXeQAGr5rF6OwdxU9OxlW5p/XxA37+eN2J0XCTfAbP2cHtsvIt0W0PdU/SHp+cG2kM9KWNJVyjp/9jNHgghzZKraq6pOk56BUwhDGcAJoKDgTQGQA06RASSexn37TodC2oBWBqmoDTTQBtRSlAWSkQukcIEkgTBJK0jSChK0giStIBGJIBmJQE6QIA/UywVYGtbJBSQCVgd1tIK6v/5rq/vGN6z2pZeshuVi9ac+ZdUf/rBVkmUqWDZWIvRKfQmExZdT5WdkoAjOHXDGMo6pwBnLu3W3jddf2nYQu/Mi4Aa2hZ5fBPnFDLoYWw9JzwtQgCsUou5iEnP5Zz9rNUxoQskc4kRuUzLpYFS/Uf1p6L0coabGOYFE4loEImikDZxSG8AFGskKjawQGiSCKAx6EaQQQRIR+FagQCgnSEROkIqcIIET1OME9YTPBO2gnnZQTzuQE9ThAnW4QC1Lw1oCat2PfmS15IFaskAtK4Oar3/dqhF1FS5QhQiqPvpRq3zmGat49FGrGDrUynv1crmolNBbSpGUqhCYF49QDNW4RQVzVdC5q62+9tIFw9idFwg3oA0397B8lJpP5ZdCcBEP5Qk/GSE32hb26GFlzz1nVaypa0naCS3NtKQTmbL7hgZramw0E3jdDOxzAqElpJ2APNAYtQK3IogCYYPcQO2ApaHyQAohpBBCMnKDVOQGSYSQ0MogdAOEkIiEoJZQ71tC1A7qJQICYS2BUCKowQlqaQW15IEaWkE1raBKIsAJqlgiViKCCjJBBeGwnKBb5n53oIuV0BKUgVweCuCF4FYPZIcyiupot97uK/RozuO4aDVid14gbPX1Xe3EoDstn/XvSYhX1Yt4Ee7hBZDHaqCYpVI1KTqhCVdQE2EiUVUtm1eVi/ymplg4gSQSdgon8CJo9HkgP98aIxE0RCLQykBukKIlpGgJSVYGPhimCIZJckGCXJDS6iAry5IsERUOEwghQVtI0BbqFQ4lAtpBfSSCOtqBEwFOUEM7qJUIyAQ1iKAaEVThBE4EL7xglThBxUc+YhU4QTnPXzZsmJUOGmQlykoQrILx4TgMyd4NiikqOcfBfoO8AC5KBLE7LwDuS4uDvW+3ApY7+TfeeJpkoO0JcDxCLnaXTwgqoheWMzF19NiUQpoSvCq/vNwJoFGEithUyppOnYqHPkMkEsupqBXoGo1qBQiggTyg7wW8ANRaUkEmSCGAFMEwSTBMEgzlBMnICZQLJEy1hHpaQj1OUM8KoY5coHagVlBHK6jDuWpZHtb+4hdWQx6ojlyghlZQjQCqyAOV3/ymVbIqqGRVUEGrK//4x62csFv29NNW+sgjVoITFLNCKGL5W4jVF1LtYV7Sa+8GRXxWxkqijDC5q3PvixZB7M7zhBvA7p79LZeBqbJPElpEdkj8sQi5PGSR+uD3vmc1Wl5pKSZrFlEiTEGOCpYTOFKV+qly2f2pKBOkoTZBQJRofA4Q8coBCoO6pnKAiFdr8dXvl4UiX3kgqTyAA6RwgCQOkMQBkjhAAgdI4AD1OEC9HIBWUC8B4AD1OEAdDpAWAPmlhjYgR6um+h35tLYqsoAXQMWXvuSyTjmrgvIPfMDKWBmUPPywFUsA5KBiWmIRwbAQJ/CZySMtBhyiDJEUs6wu4vgtnftdlAhid54H3I139L/bTg4ebMewJ9/njwZw5JNmj/NgeaT9MpZ5tbJSTbpsGAGkVJ0iS0LAuhtUxWoH3gkQQqP6fQhVvhxDx0WVLyeRkNROUqp8XZf+r8pP6T5+RRAJQDkggQA0Ft8CEggggQDqEUA9AqhDAHXeAcgCdThAHeKtxQGUXWoQQA0OUP3Tn1oVLaCK6q8iCFZ+5ztWiQAqeN6Kr33NyhFAGQIoQwBlCKD0qaes+MEHrQgBFDF/RVR1YffuVoCD5lPpmdlJkBj89yiFBMiC+4fZ+o5pEcRxdFbE7jwP2Lqbujvy8zt3tqOQLMtXxR8BhyPo9XE+z+dhS778Zav65S+tXutvSEhi/44YVSmEua9yVcFa1qmfK9zJCRCCE0MmJABZP8fKORpwECcgLwCsP0X1hyJwDuCDIBkgQQZI0AK0KkjQAuRKCqT1rAokgrr5850I1AbqyAFqW3UEwVpcwAng5ZethmeqYUVQTQ6oogVUsRys/Nu/PS0AHKACByinBZQRBEsJgqXvf7+VPPmkFT/wwGkBUBhFAwdaIcvDApxUIToPJ1WW0px6SBA+G8gplAcO9xsQ/twgjqcWEbuzlbAlb29ne9p3dpVdwGBV7Z70nAiH9B41n7z/fiv59retSnY5Z47Vq+Ko/qRSuUKZLFoCUBCM2oATgFqB7D1Co4JeBGf9gl7rc46Xc6QFwFJQ10xJBHKCSAguA0SrgSQiSMgFEIFyQEIuEIlAIpUI6iQCtQKyQB2twLtA7ahRVkMbqEYA1awGtIyt/tnPrOrHP7aqH/zAKmkDFWSA8m98w8pfesnKEEApAihBACUIoBgBFCGAQgRQSBEVIoCCfv0sn0CYT6vMQwS5zJ1aqYdE4N2gkIKrwHXz27Sx7e2b/a5hHF+xiN3ZCrgbbek+wA5jV24wQJV+MIKIP8QAc+hXR1nmFDz/vFVgk3UKVZDvJh0HSEBEEkKSqlAFNZHmW4CygCB7j9AgkiM465cYJAy91rE+/R8/7tqJRJCktSRDEchxcJ5kFASTvhUggvrICZKrV59uBxKB2gGBUGOvxQlqyQK1LAlrxo616uHDrYqVQNWvfmXVuEDVz39ulbhAJS5QgQuUkwPU8spoAaW4X8nnPmfFhMBiQmARGaCQMFxw771WMGSIFdxxh+WzLMzr2dPymLOTLPlOEJqP4wI+S/lcpa1cQN8aOtft2s3Wtk//5nEcZ7GI3dkK2Oq2PSznjkGWg0rV4zUgVfwBsD/aHuKzoyj6pMIOlVCt9KyJZbLrZb1qAd4BICUpixZJIk4ikJ3LDUSqhxeFF4aEEPV/1zpEvsKkcgAiSOEESYlAToAQnBtIbLqf2o9cIBKBG1fkBK4daKzeCVgVODfACWppBbW4QM2ECVaNC1ThAnI2tbZK2kAFDlDxwx9a+fe/b+Xf/a6V8exluEDpV79qJS++aMWf/rQVsxQsevZZK3jiCdca83GBPARwEgGcpA2c7NbNcgmEJ5jD4wrVFJPLUgHUDrQycO2hY0c7MGCIF0CrRRC78xxwN8i+tY8dIYUexH4c2cCTvy/a5nTqZLmQX8Ryr0IpWUFKE8uyqx4k1INVhRKAXMDnAZEEcS7MiUyRKojgUBAiXdBrfQbhDtE5OjctACA3UC5wLoDY5Dz6/iEZiSCBCOoRQdK3gygT1EsEBEOJoA4nqKUVyAVqCLLVrAiqCIRVr75qVbSBSlpABUvBClpA+T/+o5XjAmUEwrL/83+s9M/+zEq+8hUr/vznrfgTn7Ci556zgve+1/IffdTycIGTCCAXAeQigFzC4Anm7wQucJw5Pn7VVY70MFw3cwSOk3tsvDn9Q6M47s5A7M5zwFZd18kOYVGH27WzA1iUJ1xbYS99az/Wf4Selv/CC1b6f/+vVWGXNUrUVJVaQB0TrMlOqPr0pQxEpNsBBLmKlRNoVSAxCLJ1iULkCkr8Hnqvzz1Evo7lPEe8ELUCd30JQGLT/XRfjUEtKQqG+m7ArQ4QgVyrnnZQhxPURi6gVUEtgbCGQFg9ZoxVsyKoJAtU/Nd/WTktoPxHP7IyloNliKAUFyglDJb8+Z9b8R//sRV94QtW9MlPWuGHP2z573uf5T32mJ287z7LHTTITkDiiT597ATFdZw5Pk4WOMaS7xjzfJRW4DOWEIrhBCLJ69jR9ne81QugVSKI3XkWuAtv7dTT9nHDIwzqANa0lwGkwSD3EQoPkvqPYW9FqL+CCqlmCVVNmq6hn9ZRTbVUVh1C8E6QoAqdAGTNWLRIck4gwkQcgnBVLFGI1EgQjuRMRCJwx0Q5wNm/iNe1I/Jdy4mcQO4jEbi25FcHkQgk2HqNFweojbKAVga1BMIaWkG1bwW4QCUuUKE2gOjLyQFOAMxBCQ5QjACKEEAhAihEAAUIIA8BnEQAuQjgBAI4jgCO4QDHEICy0zHawFF9/cucHlamYo49lLn8aisXhzhJ0R1jabihXc/LJ4C1Xfvb/r59bXekRlX+HrA7wh4GcoBlzGFCTa4Sr9bGskuqpgrrdCJgEmtUTYEI6pn0ehEAGQnIERxREJaAuATZIBGKQQ4BsUkviEgMDnrPficYHSfyOd9dL4DLAqEgEEEiEoFE6XKKcoFEgAt4B5AIahFBDYGwGheoIhBW4QKVuEAFLlBOuyv/yU+s7F//1Ur/6Z+shOVgMSugIgRQiAAKEEABAshHACcRQC4COIEAjiOAYwjgKEu7owjgSNeudqRjR+e0h8kCOcytC9cRQjGoFSiMH0YE+/oPtqyrOrZKBLE7WwDLvva2c/Ddto/etJObKe2r6kX8rgh7WZYcwvqPE3IKFH6UkLHLai8AgdfVEoEqStaqliARqA+LAJxAW9cWvCAgKRE5Q1JkKixGgnAVHjiDe++Jl4voWJ3nHSB67ZeFsQJgLPUKhojACVRjRLC1ci9crJalYY2eBXFXkQXU4ipZEVQQBstZ7ZQj/LQAcIBiHKAQARQggHwEkI8A8iIBnEAAxxHAMQRwFAEcQQDKV4cRwGEEkIMAcm64wQ7huAdxAb/SCldcPhMc0nKc4L2tz2AvgLOKIHZnC7B1bbvaHga2m54kAfjKF/F6L+zlsyNKtjxwCVZYLmtUlbD29w6gbRXbak2iRKCJ1QSr2lR5mny1BW3VGrwoZNOBIByZkRAc2SI9k3iOcRDZEo53ER0Tfe7Ij7LAGQKIgqFzAfKAE4GcQGOXA0QCqMQBKnCAchygDAcowwFKEUAJAihGAEXMRwECyEcAeQggDwGcRAC5COA4AjiGAI4ggMMI4LC+3GGecxBADgI4hAAOMa8Hqe4Dcljc1wduwYdwOcFB8pcEc6hXb1vxrnP/xDB2ZwzchbbddIvtadvW9lHlO7hZdgQRn40yd6K+fQz6uBIuPbBsxAirICVXTplilUxUpUTApFVGqPJOwITWeBGQwOUGTgxUX50XBKR4MdRDVL2qVWLwQlBVi2BBr7VPn3nofYYA0oHQH6vr6bq6j+4XtQE3psABXAuTmMk1VXo2lrcVCL2c5WDZr39tpQTB0v/8TyshCBaTAYpoAYW0gHxWAXkI4CQCOMkc5bIKOMEq4BirgKOsAg6zCsihenPIADkI4BBzeQi3PUgQPHjjjXaAHLCfOd7PXIehOxSCMtlR8tkhssCm6y+hAFZci+2jwn1K/ahMAtgewYmBwe1GrQfvucdytdyRFZKQyzU5AlVSISegHUgIlUxgpdyAXioRVHsRUGUSQi2rhDqqrjYSQ52IUDVCSh3k1EGSMkNaCL5NCHqtfdH+ZgLwIvBCwDEc9JrP3PlRK3ACgPzaNWvSxDsHI/xVEf4qeb5KrF8ht1zVT7srIwSW/vznbuV
